#!/usr/bin/env python3
"""Windows-friendly equivalent of sync-env.sh.

Fetches the chatapp configuration from AWS Secrets Manager and writes a .env
file for local development. In --dev-mode, Cognito authentication is bypassed.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

import boto3


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate chatapp .env from AWS Secrets Manager")
    parser.add_argument("--region", default=os.environ.get("AWS_REGION", "us-east-1"), help="AWS region")
    parser.add_argument("--profile", default=os.environ.get("AWS_PROFILE", ""), help="AWS CLI profile")
    parser.add_argument("--dev-mode", action="store_true", help="Enable DEV_MODE (bypasses Cognito auth)")
    return parser.parse_args()


def get_secret(args: argparse.Namespace) -> dict:
    app_name = os.environ.get("APP_NAME", "htmx-chatapp")
    secret_name = os.environ.get("SECRET_NAME", f"{app_name}/appconfig")
    region = args.region
    profile = args.profile

    session_kwargs: dict = {}
    if profile:
        session_kwargs["profile_name"] = profile

    client = boto3.Session(**session_kwargs).client("secretsmanager", region_name=region)
    try:
        response = client.get_secret_value(SecretId=secret_name)
    except client.exceptions.ResourceNotFoundException as e:
        print(f"Secret '{secret_name}' not found in {region}.")
        print("Make sure the CDK stacks (at least Foundation and Agent) are deployed.")
        sys.exit(1)
    except client.exceptions.NoCredentialsError:
        print("AWS credentials not found. Run 'aws sso login --profile <your-profile>' or set credentials.")
        sys.exit(1)

    return json.loads(response["SecretString"])


def main() -> None:
    args = parse_args()
    secret = get_secret(args)

    app_name = os.environ.get("APP_NAME", "htmx-chatapp")
    region = args.region

    # Resolve account for KB source bucket fallback
    account_id = ""
    session_kwargs: dict = {}
    if args.profile:
        session_kwargs["profile_name"] = args.profile
    try:
        sts = boto3.Session(**session_kwargs).client("sts", region_name=region)
        account_id = sts.get_caller_identity()["Account"]
    except Exception as e:
        print(f"Warning: could not resolve AWS account ID: {e}")

    kb_source_bucket = secret.get("kb_source_bucket", "")
    if not kb_source_bucket:
        if account_id:
            kb_source_bucket = f"{app_name}-kb-{account_id}-{region}"
        else:
            print("Warning: could not resolve KB_SOURCE_BUCKET.")

    env_lines = [
        f"# HTMX ChatApp Environment Configuration",
        f"# Generated by sync-env.py on {datetime.now(timezone.utc).isoformat()}",
        f"# Source: AWS Secrets Manager ({os.environ.get('SECRET_NAME', f'{app_name}/appconfig')})",
        "",
        f"DEV_MODE={'true' if args.dev_mode else 'false'}",
        "DEV_USER_ID=dev-user-001",
        "",
        f"COGNITO_USER_POOL_ID={secret.get('cognito_user_pool_id', '')}",
        f"COGNITO_CLIENT_ID={secret.get('cognito_client_id', '')}",
        f"COGNITO_CLIENT_SECRET={secret.get('cognito_client_secret', '')}",
        "",
        f"AGENTCORE_RUNTIME_ARN={secret.get('agentcore_runtime_arn', '')}",
        f"MEMORY_ID={secret.get('memory_id', '')}",
        "",
        f"AWS_REGION={region}",
        "",
        f"USAGE_TABLE_NAME={secret.get('usage_table_name', 'agentcore-usage-records')}",
        f"FEEDBACK_TABLE_NAME={secret.get('feedback_table_name', 'agentcore-feedback')}",
        f"GUARDRAIL_TABLE_NAME={secret.get('guardrail_table_name', 'agentcore-guardrail-violations')}",
        f"PROMPT_TEMPLATES_TABLE_NAME={secret.get('prompt_templates_table_name', 'agentcore-prompt-templates')}",
        f"APP_SETTINGS_TABLE_NAME={secret.get('app_settings_table_name', 'agentcore-app-settings')}",
        f"RUNTIME_USAGE_TABLE_NAME={secret.get('runtime_usage_table_name', 'agentcore-runtime-usage')}",
        f"EVALUATIONS_TABLE_NAME={secret.get('evaluations_table_name', 'agentcore-evaluations')}",
        "",
        "EVALUATIONS_ENABLED=true",
        "EVALUATIONS_JUDGE_MODEL=global.anthropic.claude-haiku-4-5-20251001-v1:0",
        "",
        f"GUARDRAIL_ID={secret.get('guardrail_id', '')}",
        f"GUARDRAIL_VERSION={secret.get('guardrail_version', '')}",
        "GUARDRAIL_ENABLED=true",
        "",
        f"KB_ID={secret.get('kb_id', '')}",
        f"KB_SOURCE_BUCKET={kb_source_bucket}",
        "",
        "APP_URL=http://localhost:8080",
    ]

    env_path = Path(__file__).resolve().parent / ".env"
    env_path.write_text("\n".join(env_lines) + "\n", encoding="utf-8")
    print(f"Generated {env_path}")
    print(f"  Region: {region}")
    print(f"  DEV_MODE: {args.dev_mode}")
    print(f"  Runtime ARN: {secret.get('agentcore_runtime_arn', '')}")
    print(f"  Memory ID: {secret.get('memory_id', '')}")
    if args.dev_mode:
        print("  Cognito auth will be bypassed in DEV_MODE.")


if __name__ == "__main__":
    main()
