"""Prepare the AWS sample starter to run the onboarding domain.

This script implements Phase 5 steps 2 and 3 from Workshop_plan.md:

- Copy the onboarding domain (tools, config, models, prompts, profiles, projects)
  into `aws-samples/sample-strands-agentcore-starter`.
- Patch the starter's `agent/my_agent.py` to import and register the onboarding
  tools and to mention them in the system prompt.

It does NOT deploy AWS resources. After running it, the user still runs the
starter's CDK commands (`cdk/deploy-all.sh`) and configures the runtime env.
"""
from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path
from typing import Iterable

REPO_ROOT = Path(__file__).resolve().parents[1]
STARTER_DIR = REPO_ROOT / ".aws-samples" / "sample-strands-agentcore-starter"

DOMAIN_FILES: dict[Path, Path] = {
    # source -> destination inside starter's agent/ dir.
    #
    # IMPORTANT: the CDK Agent stack packages ONLY `agent/` as the Docker/CodeBuild
    # source (see cdk/lib/agent-stack.ts: `s3deploy.Source.asset(path.join(__dirname,
    # '../../agent'))`). Anything placed outside `agent/` (e.g. a sibling
    # `profiles/`/`projects/` dir) is silently excluded from the deployed image.
    # Everything we add must therefore live inside `agent/`.
    REPO_ROOT / "agent" / "models.py": Path("agent") / "onboarding_models.py",
    REPO_ROOT / "agent" / "prompts.py": Path("agent") / "onboarding_prompts.py",
    REPO_ROOT / "agent" / "memory_backend.py": Path("agent") / "onboarding_memory_backend.py",
}

# `agent/config.py` is NOT copied verbatim: the original computes
# PROFILES_DIR/PROJECTS_DIR/PROGRESS_DIR relative to the repo root (one level
# above `agent/`), which does not exist inside the starter's flat `agent/`
# Docker build context. We generate an equivalent module with paths relative
# to the starter's own `agent/` directory instead (see `_write_onboarding_config`).
ONBOARDING_CONFIG_TEMPLATE = '''"""Generated by accelerator/prepare_starter.py — do not edit by hand.

Paths are relative to this file's directory (the starter's flat `agent/`
Docker build context), unlike the source repo's `agent/config.py` which uses
the repo root one level above `agent/`.
"""
from __future__ import annotations

from pathlib import Path

AGENT_DIR = Path(__file__).resolve().parent
PROFILES_DIR = AGENT_DIR / "profiles"
PROJECTS_DIR = AGENT_DIR / "projects"
PROGRESS_DIR = AGENT_DIR / ".local-progress"
'''

TOOL_FILES = [
    "load_profile.py",
    "load_project.py",
    "generate_plan.py",
    "track_progress.py",
]


def clone_starter() -> None:
    """Clone the AWS starter if it isn't already present."""
    if STARTER_DIR.joinpath(".git").exists():
        print(f"Starter already present at {STARTER_DIR}")
        return

    print("Cloning AWS starter...")
    STARTER_DIR.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            "git",
            "clone",
            "https://github.com/aws-samples/sample-strands-agentcore-starter.git",
            str(STARTER_DIR),
        ],
        check=True,
    )


def _write_onboarding_config() -> None:
    dest = STARTER_DIR / "agent" / "onboarding_config.py"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(ONBOARDING_CONFIG_TEMPLATE, encoding="utf-8")


def copy_domain_files() -> None:
    """Copy onboarding domain artifacts into the starter's agent/ directory."""
    print("Copying onboarding domain files...")
    for source, dest in DOMAIN_FILES.items():
        full_dest = STARTER_DIR / dest
        full_dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, full_dest)

    _write_onboarding_config()

    starter_tools_dir = STARTER_DIR / "agent" / "tools"
    starter_tools_dir.mkdir(parents=True, exist_ok=True)
    for filename in TOOL_FILES:
        source = REPO_ROOT / "agent" / "tools" / filename
        dest = starter_tools_dir / filename
        shutil.copy2(source, dest)

    # profiles/ and projects/ MUST live inside agent/ so they are included in
    # the CodeBuild/Docker source (see the DOMAIN_FILES comment above).
    for subdir in ("profiles", "projects"):
        source = REPO_ROOT / subdir
        dest = STARTER_DIR / "agent" / subdir
        if dest.exists():
            shutil.rmtree(dest)
        shutil.copytree(source, dest)


def _rewrite_imports(file_path: Path) -> None:
    """Point copied tools at the renamed modules using the starter's flat
    import style (no `agent.` package prefix — see `my_agent.py`'s own
    `from config import AgentConfig`, since `agent/` IS the Docker WORKDIR).
    """
    text = file_path.read_text(encoding="utf-8")
    text = text.replace("from agent.config import", "from onboarding_config import")
    text = text.replace("from agent.models import", "from onboarding_models import")
    text = text.replace(
        "import agent.memory_backend as memory_backend",
        "import onboarding_memory_backend as memory_backend",
    )
    file_path.write_text(text, encoding="utf-8")


def rewrite_tool_imports() -> None:
    """Rewrite imports in copied tools so they don't clash with starter config."""
    for filename in TOOL_FILES:
        _rewrite_imports(STARTER_DIR / "agent" / "tools" / filename)


ONBOARDING_IMPORTS = """from strands import tool
from tools.load_profile import load_profile as _load_profile
from tools.load_project import load_project as _load_project
from tools.generate_plan import generate_onboarding_plan as _generate_onboarding_plan
from tools.track_progress import load_progress as _load_progress
from tools.track_progress import mark_step_done as _mark_step_done
"""

ONBOARDING_TOOLS = """        load_profile,
        load_project,
        generate_onboarding_plan,
        mark_step_done,
        load_progress,
"""

ONBOARDING_WRAPPERS = '''
# Onboarding tools must be decorated with @tool so Strands recognizes them
# (plain callables passed to Agent(tools=...) are silently ignored).
@tool
def load_profile(profile_id: str) -> dict:
    """Load a declarative onboarding profile from profiles/<id>.yaml.

    Returns expected permissions, base checklist and required approvals.
    """
    return _load_profile(profile_id)


@tool
def load_project(project_id: str) -> dict:
    """Load a declarative project from projects/<id>.yaml.

    Returns repositories, architecture, first tasks and risk notes.
    """
    return _load_project(project_id)


@tool
def generate_onboarding_plan(
    employee_name: str,
    employee_email: str,
    profile: dict,
    project: dict,
) -> str:
    """Generate a personalized onboarding plan as Markdown from a profile and a project."""
    return _generate_onboarding_plan(employee_name, employee_email, profile, project)


@tool
def mark_step_done(employee_email: str, step_id: str, note: str = "") -> dict:
    """Record a completed onboarding step for employee_email."""
    return _mark_step_done(employee_email, step_id, note)


@tool
def load_progress(employee_email: str) -> dict:
    """Load the full onboarding progress document for employee_email."""
    return _load_progress(employee_email)
'''


ONBOARDING_PROMPT_ADDITION = (
    " You can also generate developer onboarding plans: ask the user for "
    "employee name, email, profile and project, then use load_profile, "
    "load_project, generate_onboarding_plan, and mark_step_done."
)


def patch_agent() -> None:
    """Register onboarding tools in the starter's agent/my_agent.py."""
    my_agent_path = STARTER_DIR / "agent" / "my_agent.py"
    if not my_agent_path.exists():
        raise FileNotFoundError(f"Cannot patch {my_agent_path}; starter not cloned.")

    text = my_agent_path.read_text(encoding="utf-8")

    # Add onboarding tool imports and @tool-decorated wrapper functions after the
    # last starter tools import. The wrappers must be module-level so Strands
    # recognizes them as tools; plain callables passed to Agent(tools=...) are
    # silently ignored.
    marker_import = "from tools.web_search import ddg_web_search\n"
    if marker_import not in text:
        raise ValueError(f"Could not find import marker in {my_agent_path}")
    if "from tools.load_profile import load_profile as _load_profile" not in text:
        imports_and_wrappers = ONBOARDING_IMPORTS + "\n" + ONBOARDING_WRAPPERS.strip() + "\n\n"
        text = text.replace(marker_import, marker_import + imports_and_wrappers)

    # Add onboarding tools to the list.
    marker_tool = "        fetch_url_content,\n"
    if marker_tool not in text:
        raise ValueError(f"Could not find tools list marker in {my_agent_path}")
    if "        load_profile," not in text:
        text = text.replace(marker_tool, marker_tool + ONBOARDING_TOOLS)

    # Append onboarding capability to the system prompt.
    marker_prompt = "and current time/date."
    if marker_prompt not in text:
        raise ValueError(f"Could not find system prompt marker in {my_agent_path}")
    if "developer onboarding plans" not in text:
        text = text.replace(marker_prompt, marker_prompt + ONBOARDING_PROMPT_ADDITION)

    # Keep a backup and write the patched file.
    backup = my_agent_path.with_suffix(".py.bak")
    if not backup.exists():
        shutil.copy2(my_agent_path, backup)
    my_agent_path.write_text(text, encoding="utf-8")
    print(f"Patched {my_agent_path} (backup: {backup})")


def main(argv: list[str] | None = None) -> int:
    clone_starter()
    copy_domain_files()
    rewrite_tool_imports()
    patch_agent()

    print("\nStarter is prepared. Next steps:")
    print("  1) Configure runtime environment: copy starter/agent/.env.example to .env")
    print("  2) Deploy the CDK stacks:")
    print("       cd .aws-samples/sample-strands-agentcore-starter/cdk")
    print("       npm install")
    print("       ./deploy-all.sh --region us-east-1 --profile <your-profile> --ingress furl")
    print("  3) Run the UI locally:")
    print("       cd .aws-samples/sample-strands-agentcore-starter/chatapp")
    print("       ./sync-env.sh --region us-east-1 --dev-mode")
    print("       uvicorn app.main:app --reload --port 8080")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
