"""Generated by accelerator/prepare_starter.py — do not edit by hand.

Paths are relative to this file's directory (the starter's flat `agent/`
Docker build context), unlike the source repo's `agent/config.py` which uses
the repo root one level above `agent/`.
"""
from __future__ import annotations

from pathlib import Path

AGENT_DIR = Path(__file__).resolve().parent
PROFILES_DIR = AGENT_DIR / "profiles"
PROJECTS_DIR = AGENT_DIR / "projects"
PROGRESS_DIR = AGENT_DIR / ".local-progress"
